{
 "title": "gatling_graphite",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (gatling_kafka_send_ko / (gatling_kafka_send_ok + gatling_kafka_send_ko))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error(KO)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "gatling_kafka_send_ko{instance=\"graphite-exporter:9108\", job=\"gatling\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error(KO)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatling_kafka_send_ko{instance=\"graphite-exporter:9108\", job=\"gatling\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные запросы",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gatling_kafka_send_ok{instance=\"graphite-exporter:9108\", job=\"gatling\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные запросы",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatling_kafka_send_ok{instance=\"graphite-exporter:9108\", job=\"gatling\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "gatling_kafkaproducersimulation_users_Kafka_load_test_waiting",
     "legendFormat": "__auto"
    },
    {
     "expr": "gatling_kafkaproducersimulation_users_Kafka_load_test_active\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "gatling_kafkaproducersimulation_users_allUsers_done",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Успешные запросы в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(gatling_kafka_send_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Задержка отправки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gatling_kafka_send_latency_ms{instance=\"graphite-exporter:9108\", job=\"gatling\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}